controller_manager:
  ros__parameters:
    update_rate: 50
    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel_names: ["left_wheel_rear_joint", "left_wheel_fwd_joint"]
      right_wheel_names: ["right_wheel_rear_joint", "right_wheel_fwd_joint"]
      publish_rate: 50
      command_topic: "/cmd_vel"
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      publish_tf: true
      use_stamped_vel: false
